#!/bin/bash

# Karta.ba - Automatski Setup Skript
# Ovaj skript automatski kreira sve potrebne konfiguracijske fajlove

set -e

echo "================================================"
echo "  Karta.ba - Automatski Setup"
echo "================================================"
echo ""

# Boje za output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Funkcija za ispis
print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Proveri da li postoje potrebni template fajlovi
if [ ! -f "env.example" ]; then
    print_error "env.example fajl ne postoji!"
    exit 1
fi

if [ ! -f "docker-compose.example.yml" ]; then
    print_error "docker-compose.example.yml fajl ne postoji!"
    exit 1
fi

if [ ! -f "Karta.WebAPI/appsettings.Development.example.json" ]; then
    print_error "appsettings.Development.example.json fajl ne postoji!"
    exit 1
fi

echo "Izaberite mod pokretanja:"
echo ""
echo "1) ${GREEN}DEMO MODE${NC} - Brzo pokretanje sa test podacima (bez pravih Stripe/Email kredencijala)"
echo "2) ${BLUE}DEVELOPMENT MODE${NC} - Unesite svoje kredencijale za punu funkcionalnost"
echo ""
read -p "Izaberite (1 ili 2): " mode

echo ""

if [ "$mode" = "1" ]; then
    echo "${YELLOW}=== DEMO MODE ===${NC}"
    echo ""
    print_info "Koristim test podatke za brzo pokretanje..."
    
    # Kreiraj .env sa demo podacima
    cat > .env << 'EOF'
# Karta.ba Environment Variables - DEMO MODE
# Copy this file to .env and fill in your actual values

# Database Configuration
CONNECTION_STRING=Server=localhost,1433;Database=KartaDb;User Id=sa;Password=DemoPassword2024!;TrustServerCertificate=true;MultipleActiveResultSets=true;

# SQL Server Password (for Docker)
SQL_SA_PASSWORD=DemoPassword2024!

# Stripe Configuration (Test Mode - Dummy Keys)
STRIPE_SECRET_KEY=sk_test_demo_key_replace_with_real_key
STRIPE_PUBLISHABLE_KEY=pk_test_demo_key_replace_with_real_key
STRIPE_WEBHOOK_SECRET=whsec_demo_secret_replace_with_real_secret

# Email Configuration (Gmail Example - Needs Real App Password)
EMAIL_FROM_EMAIL=demo@example.com
EMAIL_SMTP_HOST=smtp.gmail.com
EMAIL_SMTP_PORT=587
EMAIL_SMTP_USERNAME=demo@example.com
EMAIL_SMTP_PASSWORD=demo_password_replace_with_app_password
EMAIL_USE_RABBITMQ=false

# RabbitMQ Configuration
RABBITMQ_HOSTNAME=rabbitmq
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest

# JWT Configuration (Auto-generated for demo)
JWT_SECRET_KEY=demo_jwt_secret_key_at_least_32_characters_long_for_security
JWT_EXPIRY_MINUTES=60
JWT_REFRESH_TOKEN_EXPIRY_DAYS=7

# Security Configuration
CORS_ALLOWED_ORIGINS=https://localhost:3000,http://localhost:3000,http://localhost:57841
RATE_LIMIT_REQUESTS_PER_MINUTE=1000
RATE_LIMIT_BURST=100

# Order Management
ORDER_CLEANUP_INTERVAL_MINUTES=60
ORDER_EXPIRATION_HOURS=24

# Event Management
EVENT_ARCHIVE_CHECK_INTERVAL_MINUTES=10

# Logging Configuration
LOG_LEVEL=Information
LOG_FILE_PATH=logs/karta-.log
LOG_RETAINED_FILE_COUNT=3

# Application Configuration
ALLOWED_HOSTS=*
EOF
    
    print_success ".env fajl kreiran (DEMO MODE)"
    
elif [ "$mode" = "2" ]; then
    echo "${BLUE}=== DEVELOPMENT MODE ===${NC}"
    echo ""
    print_info "Molimo unesite svoje kredencijale..."
    echo ""
    
    # SQL Server Password
    read -p "SQL Server Password (default: StrongPassword2024!): " sql_password
    sql_password=${sql_password:-StrongPassword2024!}
    
    # Stripe Keys
    echo ""
    print_info "Stripe ključeve možete dobiti na: https://dashboard.stripe.com/apikeys"
    read -p "Stripe Secret Key (sk_test_...): " stripe_secret
    read -p "Stripe Publishable Key (pk_test_...): " stripe_public
    read -p "Stripe Webhook Secret (whsec_...): " stripe_webhook
    
    # Email Configuration
    echo ""
    print_info "Za Gmail koristite App Password: https://myaccount.google.com/apppasswords"
    read -p "Email adresa: " email_address
    read -p "Email App Password: " email_password
    
    # JWT Secret Key
    echo ""
    read -p "JWT Secret Key (min 32 karaktera, Enter za auto-generate): " jwt_secret
    if [ -z "$jwt_secret" ]; then
        jwt_secret=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
        print_success "JWT Secret Key auto-generisan"
    fi
    
    # Kreiraj .env sa unetim podacima
    cat > .env << EOF
# Karta.ba Environment Variables
# Generated by setup.sh

# Database Configuration
CONNECTION_STRING=Server=localhost,1433;Database=KartaDb;User Id=sa;Password=${sql_password};TrustServerCertificate=true;MultipleActiveResultSets=true;

# SQL Server Password (for Docker)
SQL_SA_PASSWORD=${sql_password}

# Stripe Configuration
STRIPE_SECRET_KEY=${stripe_secret}
STRIPE_PUBLISHABLE_KEY=${stripe_public}
STRIPE_WEBHOOK_SECRET=${stripe_webhook}

# Email Configuration
EMAIL_FROM_EMAIL=${email_address}
EMAIL_SMTP_HOST=smtp.gmail.com
EMAIL_SMTP_PORT=587
EMAIL_SMTP_USERNAME=${email_address}
EMAIL_SMTP_PASSWORD=${email_password}
EMAIL_USE_RABBITMQ=false

# RabbitMQ Configuration
RABBITMQ_HOSTNAME=rabbitmq
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest

# JWT Configuration
JWT_SECRET_KEY=${jwt_secret}
JWT_EXPIRY_MINUTES=60
JWT_REFRESH_TOKEN_EXPIRY_DAYS=7

# Security Configuration
CORS_ALLOWED_ORIGINS=https://localhost:3000,http://localhost:3000,http://localhost:57841
RATE_LIMIT_REQUESTS_PER_MINUTE=1000
RATE_LIMIT_BURST=100

# Order Management
ORDER_CLEANUP_INTERVAL_MINUTES=60
ORDER_EXPIRATION_HOURS=24

# Event Management
EVENT_ARCHIVE_CHECK_INTERVAL_MINUTES=10

# Logging Configuration
LOG_LEVEL=Information
LOG_FILE_PATH=logs/karta-.log
LOG_RETAINED_FILE_COUNT=3

# Application Configuration
ALLOWED_HOSTS=*
EOF
    
    print_success ".env fajl kreiran sa vašim podacima"
    
else
    print_error "Nevažeći izbor!"
    exit 1
fi

# Kreiraj docker-compose.yml iz example fajla
print_info "Kreiram docker-compose.yml..."
cp docker-compose.example.yml docker-compose.yml
print_success "docker-compose.yml kreiran"

# Kreiraj appsettings.Development.json iz example fajla
print_info "Kreiram appsettings.Development.json..."
cp Karta.WebAPI/appsettings.Development.example.json Karta.WebAPI/appsettings.Development.json

# Zameni placeholder vrednosti sa vrednostima iz .env
source .env

# Kreiraj appsettings.Development.json sa podacima
cat > Karta.WebAPI/appsettings.Development.json << EOF
{
  "ConnectionStrings": {
    "DefaultConnection": "${CONNECTION_STRING}"
  },
  "Stripe": {    
    "SecretKey": "${STRIPE_SECRET_KEY}",
    "PublishableKey": "${STRIPE_PUBLISHABLE_KEY}",
    "WebhookSecret": "${STRIPE_WEBHOOK_SECRET}"
  },
  "Email": {
    "FromEmail": "${EMAIL_FROM_EMAIL}",
    "FromName": "Karta.ba Team (Dev)",
    "SmtpHost": "${EMAIL_SMTP_HOST}",
    "SmtpPort": ${EMAIL_SMTP_PORT},
    "SmtpUsername": "${EMAIL_SMTP_USERNAME}",
    "SmtpPassword": "${EMAIL_SMTP_PASSWORD}",
    "EnableSsl": true,
    "UseRabbitMQ": ${EMAIL_USE_RABBITMQ}
  },
  "Jwt": {
    "Key": "${JWT_SECRET_KEY}",
    "Issuer": "Karta.ba.Dev",
    "Audience": "Karta.ba.Users.Dev",
    "ExpiryMinutes": ${JWT_EXPIRY_MINUTES},
    "RefreshTokenExpiryDays": ${JWT_REFRESH_TOKEN_EXPIRY_DAYS}
  },
  "Security": {
    "CorsAllowedOrigins": "${CORS_ALLOWED_ORIGINS}",
    "RateLimitRequestsPerMinute": ${RATE_LIMIT_REQUESTS_PER_MINUTE},
    "RateLimitBurst": ${RATE_LIMIT_BURST}
  },
  "OrderCleanup": {
    "CleanupIntervalMinutes": ${ORDER_CLEANUP_INTERVAL_MINUTES},
    "OrderExpirationHours": ${ORDER_EXPIRATION_HOURS}
  },
  "Serilog": {
    "Using": ["Serilog.Sinks.Console", "Serilog.Sinks.File", "Serilog.Sinks.Debug"],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information",
        "Microsoft.AspNetCore": "Information",
        "Microsoft.EntityFrameworkCore": "Information",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext} {Message:lj} {Properties:j}{NewLine}{Exception}"
        }
      },
      {
        "Name": "File",
        "Args": {
          "path": "${LOG_FILE_PATH}",
          "rollingInterval": "Day",
          "retainedFileCountLimit": ${LOG_RETAINED_FILE_COUNT},
          "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {Level:u3}] {SourceContext} {Message:lj} {Properties:j}{NewLine}{Exception}"
        }
      },
      {
        "Name": "Debug"
      }
    ],
    "Enrich": ["FromLogContext", "WithMachineName", "WithThreadId"]
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
EOF

print_success "appsettings.Development.json kreiran"

# Kreiraj logs direktorijum ako ne postoji
if [ ! -d "logs" ]; then
    mkdir -p logs
    print_success "logs direktorijum kreiran"
fi

echo ""
echo "================================================"
print_success "Setup završen uspešno!"
echo "================================================"
echo ""

if [ "$mode" = "1" ]; then
    print_warning "DEMO MODE je aktivan!"
    echo "  - Stripe i Email kredencijali su placeholder vrednosti"
    echo "  - Za punu funkcionalnost, pokrenite ponovo sa DEVELOPMENT MODE"
    echo ""
fi

echo "Sledeći koraci:"
echo ""
echo "1. Pokrenite Docker kontejnere:"
echo "   ${GREEN}docker-compose up -d${NC}"
echo ""
echo "2. Proverite status kontejnera:"
echo "   ${GREEN}docker-compose ps${NC}"
echo ""
echo "3. Pratite logove:"
echo "   ${GREEN}docker-compose logs -f karta-api${NC}"
echo ""
echo "4. Pristupite aplikaciji:"
echo "   ${GREEN}http://localhost:8080${NC}"
echo ""
echo "Za više informacija, pogledajte README.md"
echo ""


